---

- name: httpd deletion
  hosts: dbclients
  remote_user: ansible
  become: true
  tasks:
     - name: stop the httpd service
       service: 
           name: httpd
           state: stopped
     - name: deletion of index.html
       file: 
         src: index.html
         dest: /var/www/html/index.html
         state: absent
     - name: deletion of httpd.conf
       file:
         src: httpd.conf
         dest: /etc/httpd/conf/httpd.conf
         state: absent
     - name: uninstall httpd package
       yum:
         name: httpd
         state: absent

